import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

export class MediaFileDto {
  @ApiProperty({ description: 'Unique ID of the media file', example: 'cl9abc123xyz' })
  id: string;

  @ApiProperty({ description: 'Workspace ID where this file belongs', example: 'ws_123456' })
  workspaceId: string;

  @ApiProperty({ description: 'User ID who uploaded the file', example: 'user_123' })
  userId: string;

  @ApiPropertyOptional({ description: 'Folder ID if the file is in a folder', example: 'folder_456' })
  folderId?: string;

  @ApiProperty({ description: 'Filename of the media', example: 'product_launch.mp4' })
  filename: string;

  @ApiProperty({ description: 'Original name of the uploaded file', example: 'launch_video.mp4' })
  originalName: string;

  @ApiProperty({ description: 'MIME type of the file', example: 'video/mp4' })
  mimeType: string;

  @ApiProperty({ description: 'Size of the file in bytes', example: '1048576' })
  size: string; // returning as string for JSON safety

  @ApiProperty({ description: 'URL to access the file', example: 'https://res.cloudinary.com/.../file.mp4' })
  url: string;

  @ApiProperty({ description: 'Cloudinary public ID', example: 'rooli/ws_123/product_launch' })
  publicId: string;

  @ApiPropertyOptional({ description: 'Thumbnail URL (videos only)', example: 'https://res.cloudinary.com/.../file.jpg' })
  thumbnailUrl?: string;

  @ApiPropertyOptional({ description: 'Width of the media (for images/videos)', example: 1920 })
  width?: number;

  @ApiPropertyOptional({ description: 'Height of the media (for images/videos)', example: 1080 })
  height?: number;

  @ApiPropertyOptional({ description: 'Duration in seconds (videos only)', example: 120 })
  duration?: number;

  @ApiProperty({ description: 'Whether this media was generated by AI', example: false })
  isAIGenerated: boolean;

  @ApiProperty({ description: 'Timestamp when the file was created', example: '2026-01-08T10:00:00.000Z' })
  createdAt: string;

  @ApiProperty({ description: 'Timestamp when the file was last updated', example: '2026-01-08T10:05:00.000Z' })
  updatedAt: string;
}
